# to be used when building in Jenkins
FROM us.gcr.io/platform-205701/alpine:safe-alpine3.12-sec1338-apm

# Add the capsule JAR and ci-manager-config.yml
COPY ci-manager-capsule.jar keystore.jks ci-manager-config.yml alpn-boot-8.1.13.v20181017.jar redisson-jcache.yaml protocol.info /opt/harness/

RUN wget https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64 -O /usr/bin/yq -O /usr/bin/yq
RUN chmod +x /usr/bin/yq

COPY scripts /opt/harness

RUN chmod +x /opt/harness/*.sh
RUN mkdir /opt/harness/plugins


WORKDIR /opt/harness

# set default environmental variables
ENV TAKIPI_COLLECTOR_HOST=overops-collector
ENV TAKIPI_COLLECTOR_PORT=6060
ENV JAVA_TOOL_OPTIONS=-agentpath:/opt/harness/takipi/lib/libTakipiAgent.so

# Download and install the agent - extracts into the `takipi` folder.
# NOTE: Use the correct Agent for your OS
RUN curl -sL https://s3.amazonaws.com/app-takipi-com/deploy/linux/takipi-agent-latest.tar.gz | tar -xvzf - -C /opt/harness

CMD [ "./run.sh" ]