# Builder Stage
FROM us.gcr.io/platform-205701/alpine:jdk-experimental AS builder

# Add the capsule JAR and config.yml

COPY ci-manager-capsule.jar keystore.jks ci-manager-config.yml alpn-boot-8.1.13.v20181017.jar /opt/harness/

COPY scripts /opt/harness

RUN chmod +x /opt/harness/*.sh \
    && mkdir /opt/harness/plugins \
    && chown -R 65534:65534 /opt/harness/ /tmp \
    && chmod 700 -R /opt/harness/ \
    && chmod 700 -R /tmp

# Final Stage
FROM us.gcr.io/platform-205701/alpine:jdk-experimental

RUN addgroup -S 65534 && adduser -S 65534 -G 65534

COPY --from=builder /opt/harness/ /opt/harness/
COPY /tmp /tmp

USER 65534

WORKDIR /opt/harness

CMD [ "./run.sh" ]
