# to be used when building in Jenkins
FROM harness/openjdk8:x86_64-alpine-jre8u242-b08

# Add the capsule JAR and config.yml
COPY keystore.jks /opt/harness/
COPY config.yml /opt/harness/
COPY accesscontrol-service-capsule.jar /opt/harness/
COPY scripts /opt/harness/

RUN set -x \
    && mkdir /opt/harness/plugins \
    && chown harness:harness -R /opt/harness \
    && chmod 500 /opt/harness/*.sh

USER harness

CMD [ "./run.sh" ]
