-- Copyright 2021 Harness Inc.
-- 
-- Licensed under the Apache License, Version 2.0
-- http://www.apache.org/licenses/LICENSE-2.0

BEGIN;
ALTER TABLE BILLING_DATA ADD COLUMN IF NOT EXISTS NETWORKCOST DOUBLE PRECISION;
ALTER TABLE BILLING_DATA_HOURLY ADD COLUMN IF NOT EXISTS NETWORKCOST DOUBLE PRECISION;
ALTER TABLE BILLING_DATA ADD COLUMN IF NOT EXISTS PRICINGSOURCE TEXT;
ALTER TABLE BILLING_DATA_HOURLY ADD COLUMN IF NOT EXISTS PRICINGSOURCE TEXT;
COMMIT;
