-- Copyright 2021 Harness Inc.
-- 
-- Licensed under the Apache License, Version 2.0
-- http://www.apache.org/licenses/LICENSE-2.0

BEGIN;
ALTER TABLE BILLING_DATA ADD COLUMN SYSTEMCOST DOUBLE PRECISION;
ALTER TABLE BILLING_DATA ADD COLUMN CPUSYSTEMCOST DOUBLE PRECISION;
ALTER TABLE BILLING_DATA ADD COLUMN MEMORYSYSTEMCOST DOUBLE PRECISION;
COMMIT;
