-- Copyright 2021 Harness Inc.
-- 
-- Licensed under the Apache License, Version 2.0
-- http://www.apache.org/licenses/LICENSE-2.0

BEGIN;
ALTER TABLE BUDGET_ALERTS ADD COLUMN ALERTBASEDON TEXT NOT NULL DEFAULT 'ACTUAL_COST';
UPDATE BUDGET_ALERTS SET ALERTBASEDON = 'FORECASTED_COST' WHERE ACTUALCOST < BUDGETEDCOST*ALERTTHRESHOLD/100;
COMMIT;
