BEGIN;
CREATE TABLE IF NOT EXISTS PROJECT_SUMMARY_DATA (
        ACCOUNT_IDENTIFIER TEXT NOT NULL,
        ORG_IDENTIFIER TEXT NOT NULL,
        PROJECT_IDENTIFIER TEXT NOT NULL,
        NAME TEXT NOT NULL ,
        DEPLOYMENT_COUNT INTEGER,
        BUILD_COUNT INTEGER,
        FEATURE_FLAGS_COUNT INTEGER,
        TOTAL_COUNT INTEGER
);
COMMIT;

