-- Copyright 2021 Harness Inc.
-- 
-- Licensed under the Apache License, Version 2.0
-- http://www.apache.org/licenses/LICENSE-2.0

BEGIN;
CREATE TABLE IF NOT EXISTS COST_EVENT_DATA (
	STARTTIME TIMESTAMPTZ NOT NULL,
	ACCOUNTID TEXT NOT NULL,
	SETTINGID TEXT,
	CLUSTERID TEXT,
	CLUSTERTYPE TEXT,
	INSTANCEID TEXT,
	INSTANCETYPE TEXT,
	APPID TEXT,
	SERVICEID TEXT,
	ENVID TEXT,
	CLOUDPROVIDERID TEXT,
	DEPLOYMENTID TEXT,
	CLOUDPROVIDER TEXT,
	EVENTDESCRIPTION TEXT,
	COSTEVENTTYPE TEXT,
	COSTEVENTSOURCE TEXT,
	NAMESPACE TEXT,
	WORKLOADNAME TEXT,
	WORKLOADTYPE TEXT,
	CLOUDSERVICENAME TEXT,
	TASKID TEXT,
	LAUNCHTYPE TEXT,
	BILLINGAMOUNT DOUBLE PRECISION,
	OLDYAMLREF TEXT,
	NEWYAMLREF TEXT
);
COMMIT;

SELECT CREATE_HYPERTABLE('COST_EVENT_DATA','starttime',if_not_exists => TRUE);
