-- Copyright 2021 Harness Inc.
-- 
-- Licensed under the Apache License, Version 2.0
-- http://www.apache.org/licenses/LICENSE-2.0

BEGIN;
ALTER TABLE DEPLOYMENT ADD COLUMN IF NOT EXISTS TAGS HSTORE;
CREATE INDEX IF NOT EXISTS DEPLOYMENT_TAGS_GIN_INDEX ON DEPLOYMENT USING GIN(TAGS);
COMMIT ;
