-- Copyright 2021 Harness Inc.
-- 
-- Licensed under the Apache License, Version 2.0
-- http://www.apache.org/licenses/LICENSE-2.0

BEGIN;

ALTER TABLE ANOMALIES ADD COLUMN IF NOT EXISTS SLACKDAILYNOTIFICATION BOOLEAN DEFAULT FALSE;
ALTER TABLE ANOMALIES ADD COLUMN IF NOT EXISTS SLACKINSTANTNOTIFICATION BOOLEAN DEFAULT FALSE;
ALTER TABLE ANOMALIES ADD COLUMN IF NOT EXISTS SLACKWEEKLYNOTIFICATION BOOLEAN DEFAULT FALSE;

COMMIT;
