-- Copyright 2021 Harness Inc.
-- 
-- Licensed under the Apache License, Version 2.0
-- http://www.apache.org/licenses/LICENSE-2.0

---------- ACTIVE_POD_COUNT TABLE START ------------
BEGIN;
CREATE TABLE IF NOT EXISTS ACTIVE_POD_COUNT (
  STARTTIME TIMESTAMPTZ NOT NULL,
  ENDTIME TIMESTAMPTZ NOT NULL,
	ACCOUNTID TEXT NOT NULL,
	CLUSTERID TEXT NOT NULL,
	INSTANCEID TEXT NOT NULL,
	PODCOUNT DOUBLE PRECISION
);
COMMIT;
SELECT CREATE_HYPERTABLE('ACTIVE_POD_COUNT','starttime',if_not_exists => TRUE);

BEGIN;
CREATE INDEX IF NOT EXISTS ACTIVE_POD_COUNT_ACCOUNTID_INDEX ON ACTIVE_POD_COUNT(ACCOUNTID, CLUSTERID, INSTANCEID, STARTTIME DESC);
COMMIT;

---------- ACTIVE_POD_COUNT TABLE END ------------
