---------- BUDGET_HISTORY TABLE START ------------
BEGIN;
CREATE TABLE IF NOT EXISTS BUDGET_HISTORY (
	BUDGETID TEXT NOT NULL,
	ACCOUNTID TEXT NOT NULL,
	BUDGETEDAMOUNT DOUBLE PRECISION,
	UPDATETIME TIMESTAMPTZ NOT NULL,
	BUDGETSTARTTIME TIMESTAMPTZ NOT NULL
);
COMMIT;
SELECT CREATE_HYPERTABLE('BUDGET_HISTORY','updatetime',if_not_exists => TRUE);

---------- BUDGET_HISTORY TABLE END ------------