-- Copyright 2021 Harness Inc.
-- 
-- Licensed under the Apache License, Version 2.0
-- http://www.apache.org/licenses/LICENSE-2.0

BEGIN;
ALTER TABLE DEPLOYMENT ADD COLUMN IF NOT EXISTS ENVTYPES TEXT[];
ALTER TABLE DEPLOYMENT ADD COLUMN IF NOT EXISTS PARENT_EXECUTION TEXT;
ALTER TABLE DEPLOYMENT ADD COLUMN IF NOT EXISTS STAGENAME TEXT;

CREATE INDEX IF NOT EXISTS DEPLOYMENT_ENV_TYPE_INDEX ON DEPLOYMENT(envtypes,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_PARENT_EXECUTION_INDEX ON DEPLOYMENT(parent_execution,ENDTIME DESC);
CREATE INDEX IF NOT EXISTS DEPLOYMENT_STAGENAME_INDEX ON DEPLOYMENT(stagename,ENDTIME DESC);

COMMIT ;
