-- Copyright 2021 Harness Inc.
-- 
-- Licensed under the Apache License, Version 2.0
-- http://www.apache.org/licenses/LICENSE-2.0

BEGIN;
CREATE UNIQUE INDEX IF NOT EXISTS UTILIZATION_DATA_UNIQUE_INDEX ON UTILIZATION_DATA(ACCOUNTID, SETTINGID, CLUSTERID, INSTANCEID, INSTANCETYPE, STARTTIME DESC);
COMMIT;

BEGIN;
CREATE UNIQUE INDEX IF NOT EXISTS KUBERNETES_UTILIZATION_DATA_UNIQUE_INDEX ON KUBERNETES_UTILIZATION_DATA(ACCOUNTID, SETTINGID, CLUSTERID, INSTANCEID, INSTANCETYPE, STARTTIME DESC);
COMMIT;
