FROM us.gcr.io/platform-205701/alpine:safe-alpine3.12-jdk11

#COPY --chown=65534:65534 alpn-boot-8.1.13.v20181017.jar /opt/harness/
COPY --chown=65534:65534 keystore.jks /opt/harness/
COPY --chown=65534:65534 config.yml /opt/harness/
COPY --chown=65534:65534 classpath_metadata.json /opt/harness/
COPY --chown=65534:65534 platform-service-capsule.jar /opt/harness/
COPY --chown=65534:65534 scripts /opt/harness/

RUN chmod 500 /opt/harness/*.sh

CMD [ "./run.sh" ]
