package io.harness.cvng;

public enum DataCollectionRequestType {
  SPLUNK_SAVED_SEARCHES,
  STACKDRIVER_DASHBOARD_LIST,
  STACKDRIVER_DASHBOARD_GET,
  STACKDRIVER_SAMPLE_DATA,
  APPDYNAMICS_FETCH_APPS,
  APPDYNAMICS_FETCH_TIERS,
}
