# Dropwizard config
server:
  allowedMethods: ["GET"]
  adminConnectors: []
  applicationConnectors:
    - type: http
      port: 3460
      maxRequestHeaderSize: 100KiB
  rootPath: /api
  maxThreads: 1024

# Delegate Config
accountId: kmpySmUISimoRrJL6NL73w
accountSecret: 2f6b0988b6fb3370073c3d0505baee59
managerUrl: https://localhost:9090/api/
verificationServiceUrl: https://localhost:7070/verification/
cvNextGenUrl: https://localhost:6060/cv/api/
heartbeatIntervalMs: 60000
localDiskPath: /tmp
doUpgrade: false
pollForTasks: false
description: description here
managerTarget: localhost:9880
managerAuthority: localhost
queueFilePath: ../eventQueue
grpcServiceEnabled: true
grpcServiceConnectorPort: 8080
logStreamingServiceBaseUrl: http://localhost:8079
clientToolsDownloadDisabled: true
installClientToolsInBackground: true
versionCheckDisabled: true
