# to be used when building in Jenkins
FROM harness/manager-openjdk-8u242:x86_64-alpine-jre8u242-b08

# Add the capsule JAR and config.yml
COPY keystore.jks /opt/harness/
COPY verification-config.yml /opt/harness/
COPY verification-capsule.jar /opt/harness/
COPY scripts /opt/harness/

RUN set -x \
    && mkdir -p /opt/harness/plugins \
    && chown harness:harness -R /opt/harness \
    && chmod 500 /opt/harness/*.sh

USER harness

CMD [ "./run.sh" ]
