# to be used when building in Jenkins
FROM harness/manager-openjdk-8u242:x86_64-alpine-jre8u242-b08

COPY --chown=harness:harness keystore.jks /opt/harness/
COPY --chown=harness:harness verification-config.yml /opt/harness/
COPY --chown=harness:harness verification-capsule.jar /opt/harness/
COPY --chown=harness:harness scripts /opt/harness/

RUN  chmod 500 /opt/harness/*.sh

CMD [ "./run.sh" ]
