# to be used when building in Jenkins
FROM ubuntu:20.04

RUN apt-get update && \
    apt-get -y install curl unzip gnupg2 libgcrypt20 locales && \
    locale-gen en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    apt-get clean

RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

COPY apt-source-list /etc/apt/sources.list.d/kubernetes.list

RUN apt-get update && apt-get install -y kubectl

COPY scripts /opt/harness-delegate/

RUN curl -s -L -o go-template https://app.harness.io/storage/harness-download/snapshot-go-template/release/v0.4/bin/darwin/go-template
COPY go-template /opt/harness-delegate/

RUN curl -s -L -o helm https://app.harness.io/storage/harness-download/harness-helm/release/v2.13.1/bin/darwin/amd64/helm
COPY helm /opt/harness-delegate/

RUN curl -s -L -o chartmuseum https://app.harness.io/storage/harness-download/harness-chartmuseum/release/v0.13.0/bin/darwin/amd64/chartmuseum
COPY chartmuseum /opt/harness-delegate/

RUN curl -s -L -o scm https://app.harness.io/storage/harness-download/harness-scm/release/87448d72/bin/darwin/amd64/scm
COPY scm /opt/harness-delegate/

RUN curl -s -L -o terraform-config-inspect https://app.harness.io/storage/harness-download/harness-terraform-config-inspect/v1.1/darwin/amd64/terraform-config-inspect
COPY terraform-config-inspect /opt/harness-delegate/

RUN curl -s -L -o harness-pywinrm https://app.harness.io/storage/harness-download/snapshot-harness-pywinrm/release/v0.4-dev/bin/darwin/amd64/harness-pywinrm
COPY harness-pywinrm /opt/harness-delegate/

RUN curl -s -L -o oc https://app.harness.io/storage/harness-download/harness-oc/release/v4.2.16/bin/darwin/amd64/oc
COPY oc /opt/harness-delegate/

RUN curl -s -L -o kustomize https://app.harness.io/storage/harness-download/harness-kustomize/release/v3.5.4/bin/darwin/amd64/kustomize
COPY kustomize /opt/harness-delegate/

RUN chmod +x /opt/harness-delegate/*.sh

WORKDIR /opt/harness-delegate

RUN curl -s https://app.harness.io/storage/wingsdelegates/jre/openjdk-8u242/jre_x64_linux_8u242b08.tar.gz | tar -xz
RUN curl -#k https://app.harness.io/public/shared/watchers/builds/openjdk-8u242/72306/watcher.jar -o watcher.jar
CMD ./entrypoint.sh && bash -c ' \
    while [[ ! -e watcher.log ]]; do sleep 1s; done; tail -F watcher.log & \
    while [[ ! -e delegate.log ]]; do sleep 1s; done; tail -F delegate.log'
