FROM ubuntu:20.04

RUN apt-get update && \
    apt-get -y install curl unzip gnupg2 libgcrypt20 locales && \
    locale-gen en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    apt-get clean

RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

COPY apt-source-list /etc/apt/sources.list.d/kubernetes.list

RUN apt-get update && apt-get install -y kubectl

COPY scripts /opt/harness-delegate/

RUN chmod +x /opt/harness-delegate/*.sh

COPY --from=appdynamics/java-agent:latest /opt/appdynamics /opt/appdynamics

ENV APPDYNAMICS_CONTROLLER_HOST_NAME="harness-test.saas.appdynamics.com"
ENV APPDYNAMICS_CONTROLLER_PORT="443"
ENV APPDYNAMICS_AGENT_ACCOUNT_NAME="harness-test"
ENV APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY="g99q8cbgwccb"
ENV APPDYNAMICS_CONTROLLER_SSL_ENABLED="true"
ENV APPDYNAMICS_AGENT_APPLICATION_NAME="delegate-app-monitoring"
ENV APPDYNAMICS_AGENT_TIER_NAME="delegate-app-tier"
ENV ENABLE_APPDYNAMICS="true"
ENV APPDYNAMICS_AGENT_NODE_NAME="delegate-app-node"

WORKDIR /opt/harness-delegate

RUN curl -s https://app.harness.io/storage/wingsdelegates/jre/openjdk-8u242/jre_x64_linux_8u242b08.tar.gz | tar -xz
RUN curl -#k https://app.harness.io/public/shared/watchers/builds/openjdk-8u242/72500/watcher.jar -o watcher.jar
CMD ./entrypoint.sh && bash -c ' \
    while [[ ! -e watcher.log ]]; do sleep 1s; done; tail -F watcher.log & \
    while [[ ! -e delegate.log ]]; do sleep 1s; done; tail -F delegate.log'