DEFAULT_API_KEY = "cHg3eGRfQkZSQ2ktcGZXUFlYVmp2dzo6ZEs3bkRPRVNGcG1XcWhuaEVRR2R3NjN6ZnVqYlFMZ1ZZT2pmNGEyb3dBMVdJQlBuNTVXclVVdEZjYWdCQkdJd0xwMFdPa3RxUml4VTRwRWw="
DEFAULT_ACCOUNT_ID = "px7xd_BFRCi-pfWPYXVjvw"
APP_DOMAIN_QA = "https://qa.harness.io/gateway"
