# Builder Stage
FROM harness/alpine:safe-alpine3.12-sec1096 AS builder

# Add the capsule JAR and config.yml

COPY pipeline-service-capsule.jar config.yml alpn-boot-8.1.13.v20181017.jar /opt/harness/

COPY scripts /opt/harness

RUN chmod +x /opt/harness/*.sh \
    && mkdir /opt/harness/plugins \
    && chown -R 65534:65534 /opt/harness/ \
    && chmod 700 -R /opt/harness/

# Final Stage
FROM harness/alpine:safe-alpine3.12-sec1096

RUN addgroup -S 65534 && adduser -S 65534 -G 65534

COPY --from=builder /opt/harness/ /opt/harness/

RUN wget https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64 -O /usr/bin/yq -O /usr/bin/yq \
    && chmod +x /usr/bin/yq \
    && chown -R 65534:65534 /tmp \
    && chmod 700 -R /tmp

USER 65534

WORKDIR /opt/harness

CMD [ "./run.sh" ]