package io.harness.subscription.constant;

public enum Prices {
  CD_ENTERPRISE_SERVICE_MONTHLY,
  CD_ENTERPRISE_SERVICE_YEARLY,
  CD_ENTERPRISE_PREMIUM_SUPPORT_MONTHLY,
  CD_ENTERPRISE_PREMIUM_SUPPORT_YEARLY,
  CI_ENTERPRISE_DEVELOPERS_MONTHLY,
  CI_ENTERPRISE_DEVELOPERS_YEARLY,
  CI_TEAM_DEVELOPERS_MONTHLY,
  CI_TEAM_DEVELOPERS_YEARLY
}
