FROM adoptopenjdk/openjdk8:x86_64-alpine-jdk8u242-b08

RUN apk add --no-cache bash

RUN set -x \
    && wget https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64 -O /usr/bin/yq \
    && chmod +x /usr/bin/yq

RUN set -x \
    && addgroup -S 65534 \
    && adduser -S 65534 -G 65534 \
    && mkdir -p /opt/harness/plugins \
    && chown -R 65534:65534 /opt/harness \
    && chmod -R 700 /opt/harness

WORKDIR /opt/harness

USER 65534
