# to be used when building in Jenkins
FROM harness/manager-openjdk-8u242:x86_64-alpine-jre8u242-b08

# Add the capsule JAR and config.yml
COPY alpn-boot-8.1.13.v20181017.jar /opt/harness/
COPY newrelic.yml /opt/harness/
COPY keystore.jks /opt/harness/
COPY hazelcast.xml /opt/harness/
COPY redisson-jcache.yaml /opt/harness/
COPY config.yml /opt/harness/
COPY rest-capsule.jar /opt/harness/
COPY scripts /opt/harness/

RUN set -x \
    && mkdir /opt/harness/plugins \
    && chown harness:harness -R /opt/harness \
    && chmod 500 /opt/harness/*.sh

USER harness

CMD [ "./run.sh" ]
