package io.harness.ccm.commons.entities;

public enum CCMField {
  PERSPECTIVE_ID,
  WORKLOAD,
  WORKLOAD_TYPE,
  CLUSTER_ID,
  CLUSTER_NAME,
  NAMESPACE,
  GCP_PRODUCT,
  GCP_PROJECT,
  GCP_SKU_ID,
  GCP_SKU_DESCRIPTION,
  AWS_ACCOUNT,
  AWS_SERVICE,
  ANOMALY_DATE
}
